# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Studios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Studios
pod 'GoogleMaps'
pod 'GooglePlaces'
pod "EFAutoScrollLabel"
pod 'RealmSwift'
pod 'Cosmos'
pod 'ActiveLabel'
pod 'Moya'
pod 'Moya-ObjectMapper', '2.9'
pod 'FirebaseAuth'
pod 'FirebaseDatabase'
end
